// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var LocalforageMinJs = require("./vendor/localforage.min.js");

function getItem(prim) {
  return LocalforageMinJs.getItem(prim);
}

function setItem(prim, prim$1) {
  return LocalforageMinJs.setItem(prim, prim$1);
}

exports.getItem = getItem;
exports.setItem = setItem;
/* ./vendor/localforage.min.js Not a pure module */
